### ISSUE TITLE
:bomb: `Bug`: The Command `dtm apply xxx` Got a Panic Error

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#530]
### What happened?

When I execute `dtm apply xxx` at a directory without `config.yaml`, I got the logs like below:

```sh
2022-05-18 20:06:05 ℹ [INFO]  Apply started.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1052d0ad8]

goroutine 1 [running]:
github.com/devstream-io/devstream/internal/pkg/configloader.validateConfigFile(0x140001c6f00)
	github.com/devstream-io/devstream/internal/pkg/configloader/validation.go:90 +0x268
github.com/devstream-io/devstream/internal/pkg/configloader.LoadConf({0x1055ccc5a, 0xb})
	github.com/devstream-io/devstream/internal/pkg/configloader/config.go:84 +0x4c0
github.com/devstream-io/devstream/internal/pkg/pluginengine.Apply({0x1055ccc5a, 0xb}, 0x0)
	github.com/devstream-io/devstream/internal/pkg/pluginengine/cmd_apply.go:15 +0x48
main.applyCMDFunc(0x105a2b840, {0x1400006d830, 0x1, 0x1})
	github.com/devstream-io/devstream/cmd/devstream/apply.go:22 +0x98
github.com/spf13/cobra.(*Command).execute(0x105a2b840, {0x1400006d800, 0x1, 0x1})
	github.com/spf13/cobra@v1.4.0/command.go:860 +0xa04
github.com/spf13/cobra.(*Command).ExecuteC(0x105a2bfc0)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x7b8
github.com/spf13/cobra.(*Command).Execute(0x105a2bfc0)
	github.com/spf13/cobra@v1.4.0/command.go:902 +0x30
main.main()
	github.com/devstream-io/devstream/cmd/devstream/main.go:99 +0x30
```

dtm should tell me that I need a config file instead of raising a "panic: runtime error: invalid memory address or nil pointer dereference"

### How to reproduce?

```sh
cd /tmp
mdkir test123321
cd test123321
dtm apply xxx
```

### DevStream version (to find out the version run: dtm version)

v0.5.0

**Comment by shubham-cmyk** [comment]
Hi I have run the same command dtm apply without a config file but not facing the same bug. 
![Screenshot from 2022-05-19 00-06-40](https://user-images.githubusercontent.com/69793468/169135630-6af0cf8f-92b6-4421-b61e-fc4cd64181e6.png)

**Comment by shubham-cmyk** [comment]
Can i get more details about it ??

**Comment by daniel-hutao** [comment]
@shubham-cmyk I'm so sorry, this panic raised in version v0.5.0 and I just found it has been fixed at main branch.
